# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticketmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='UserTicketModel',
        ),
    ]
