# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('demo', '0002_auto_20180802_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ttsx_cart',
            },
        ),
        migrations.RenameModel(
            old_name='GoodsInfo',
            new_name='Goods',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Goods'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel'),
        ),
    ]
