# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='sex',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='addressee_p',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='direction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password_c',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='recipients',
            field=models.CharField(default='', max_length=10),
        ),
    ]
